name: Hexo

on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: hexo
          submodules: true
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Update hexo content
        run: |
          npx hexo clean
          npx hexo generate
      - name: Config git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Publish new site
        if: github.ref == 'refs/heads/hexo'
        run: |
          mkdir .deploy
          cd .deploy
          REPO_URL=https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git clone --depth 1 --branch master --single-branch ${REPO_URL} . || (git init && git remote add -t master origin ${REPO_URL})
          rm -rf ./*
          cp -r ../public/* .
          git add -A .
          COMMIT_MESSAGE="Site updated on `date '+%Y-%m-%d %H:%M:%S'`"
          git commit -m "${COMMIT_MESSAGE}"
          git branch -m master
          git push -q -u origin master
      - name: Run Stoat Action
        uses: stoat-dev/stoat-action@v0
        if: always()
